services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha-dev
    restart: "no"
    ports:
      - "8123:8123"
    volumes:
      - ./custom_components/chores:/config/custom_components/chores
    environment:
      - TZ=Europe/London
