DOMAIN = "chores"
INTERVAL_DAYS = "days"
INTERVAL_WEEKS = "weeks"
INTERVAL_UNITS = (INTERVAL_DAYS, INTERVAL_WEEKS)

STATUS_DONE = "done"
STATUS_OVERDUE = "overdue"
STATUS_SNOOZED = "snoozed"
STATUS_OPTIONS = [STATUS_DONE, STATUS_OVERDUE, STATUS_SNOOZED]
