complete:
  target:
    device:
      integration: chores

snooze:
  target:
    device:
      integration: chores
  fields:
    snooze_days:
      required: false
      selector:
        number:
          min: 1
          step: 1
          mode: box
    snooze_weeks:
      required: false
      selector:
        number:
          min: 1
          step: 1
          mode: box
    snooze_until:
      required: false
      selector:
        date:

unsnooze:
  target:
    device:
      integration: chores
