name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hassfest:
    name: hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  check:
    name: Lint, typecheck & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.14"
          version: "0.11.19"
      - run: make venv
      - run: make check

  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            ci
          requireScope: false
          ignoreLabels: |
            autorelease: pending
